{% set name = "SharedArray" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a1f3aad1f1f40e84cbfda0e0a33d3f5148551f5a65a0d274d04d8988e69a20ac

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - SharedArray
  commands:
    - pip check

about:
  home: https://gitlab.com/tenzing/shared-array
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE.txt
  summary: 'SharedArray python/numpy extension'

  description: |
    This is a simple python extension that lets you share numpy arrays
    with other processes on the same computer. It uses either shared files
    or POSIX shared memory as data stores and therefore should work on
    most operating systems.
  doc_url: https://gitlab.com/tenzing/shared-array
  dev_url: https://gitlab.com/tenzing/shared-array

extra:
  recipe-maintainers:
    - jan-janssen
