travis:
  secure:
    BINSTAR_TOKEN: DsFKa9Tbi8yJFfEyPbNablfbGKRR5shhP6iPvXP4H5qC2RX/6IbXzT0i8NZ7sYbrUS+4tfTqns8ZpKQP4pT4KSyeq65BvRGS+vhXgiYNro41NiNhhT3HR0vyF+WwquYovKRebkPjmga3j2qnxySKBUZf9csGqqqa5he3vIUb3WGR6E2b7ygWUJ2hbLWhgIqSHr+afRCpsNb+Sj3smzLqP2LD1UN/pSffbLKgewGWVb9s8uCXK7N6h910Y41T4+8WZvyf/5xzPzjlHk/WFCt7RgfrAbcBX1luKB1YDGMLKT2Sxy7rN0h8lsL6FK6rtb/pVuzAvL3uXQC5BNUzNHAVGOWvpxtEuCDvyKEjqOXQtURo8Va8c7X3cOB3dDdei4Dy2AlX0+0wgCwhe31NdZjGGR58VhSYxMmKIJcuy051t52BVH6KAJL+I8HYC9BteaYBcOD68yqWlUSaW4PdA7a4/h+JfZiT7T1mifX5szMODNnV7mLgFtcEawSPV5DDgKsnwo3y0pmJyyQFPuiUUrB76312tWmKb+pQldIJBlG87wBCaF68/kFwMhsl3bsc7XKT98vSEEMK/txuREWSW7WxtW2HSmHZOetYAtl7fOa8M+/YCVajnO7VuGIa/FVykqGiUt9awGFVA0Sj0QoY42Ke5RivwbxfFudYACB1cs/MaI4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
conda_forge_output_validation: true
